version: "3"

services:
  mamp_webserver:
    build: 
      context: ./bin/webserver
    container_name: 'mamp_webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mamp_mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mamp_mysql:
    build: ./bin/mysql
    container_name: 'mamp_mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
  mamp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'mamp_phpmyadmin'
    links:
      - mamp_mysql
    environment:
      PMA_HOST: mamp_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  mamp_redis:
    container_name: 'mamp_redis'
    image: redis:latest
    ports:
      - "6379:6379"
